db.products.insert({
   "KeyboardCombo":{
      "price":30,
      "quantity":1,
      "url":"https://cpen400a.herokuapp.com/images/KeyboardCombo.png"
   },
   "Mice":{
      "price":7,
      "quantity":4,
      "url":"https://cpen400a.herokuapp.com/images/Mice.png"
   },
   "PC1":{
      "price":329,
      "quantity":10,
      "url":"https://cpen400a.herokuapp.com/images/PC1.png"
   },
   "PC2":{
      "price":375,
      "quantity":8,
      "url":"https://cpen400a.herokuapp.com/images/PC2.png"
   },
   "PC3":{
      "price":345,
      "quantity":10,
      "url":"https://cpen400a.herokuapp.com/images/PC3.png"
   },
   "Tent":{
      "price":30,
      "quantity":10,
      "url":"https://cpen400a.herokuapp.com/images/Tent.png"
   },
   "Box1":{
      "price":6,
      "quantity":5,
      "url":"https://cpen400a.herokuapp.com/images/Box1.png"
   },
   "Box2":{
      "price":7,
      "quantity":3,
      "url":"https://cpen400a.herokuapp.com/images/Box2.png"
   },
   "Clothes1":{
      "price":20,
      "quantity":10,
      "url":"https://cpen400a.herokuapp.com/images/Clothes1.png"
   },
   "Clothes2":{
      "price":25,
      "quantity":5,
      "url":"https://cpen400a.herokuapp.com/images/Clothes2.png"
   },
   "Jeans":{
      "price":36,
      "quantity":6,
      "url":"https://cpen400a.herokuapp.com/images/Jeans.png"
   },
   "Keyboard":{
      "price":18,
      "quantity":4,
      "url":"https://cpen400a.herokuapp.com/images/Keyboard.png"
   }
 });